### ISSUE TITLE
online access?

### ISSUE THREAD

**Issue by atks** [ksahlin/NGSpeciesID#13]
@ksahlin - dear kristoffer, does your lab happen to have a web access to your NGSpeciesID pipeline?

**Comment by ksahlin** [comment]
Hi @atks, Definitely: https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/ece3.7146

**Comment by atks** [comment]
@ksahlin - I meant the pipeline, not the paper. :)

**Comment by ksahlin** [comment]
What do you mean by web access in this context? The NGSpeciesID pipeline is freely available here at github.

**Comment by atks** [comment]
@ksahlin - something like this https://www.genomedetective.com/

**Comment by ksahlin** [comment]
Ah okay! No, there is no such access.

**Comment by atks** [comment]
@ksahlin - you should consider it!  :)  I will try building from scratch anyway because it is applicable to at least another analyses we have for virus.

**Comment by ksahlin** [comment]
The topic has been brought up before. If I manage to get some funding for it, sure :)
