### ISSUE TITLE
Is there any specific reason to use the outdated medaka==0.11.5 and openblas==0.3.3 versions?

### ISSUE THREAD

**Issue by Coppini** [ksahlin/NGSpeciesID#17]
I tried using NGSpeciesID with more recent versions (simply installing `medaka` and `openblas` without setting the version) and it seemed to work fine. I did get slightly different outputs, but I'm assuming that has to do with `medaka` improvements from `0.11.5` to `1.5.0`.

Was there any specific reason to tie these two dependencies to these two specific versions?

**Comment by ksahlin** [comment]
There was really no reason besides we verified that the installation worked on our machines using these versions. The openblas was a package required to make medaka work on iOS, for reference see [here](https://github.com/ksahlin/NGSpeciesID/issues/1#issuecomment-588099798). It is possible that they have removed/relaxed this requirement.
