### ISSUE TITLE
medaka consensus qualities

### ISSUE THREAD

**Issue by pecholleyn** [ksahlin/NGSpeciesID#26]
Hi, with the latest version of [medaka](https://github.com/nanoporetech/medaka/releases/tag/v1.8.1), it is now possible to obtain a FASTQ file, with qualities, instead of FASTA for consensus generated. I would be very interested to have this `-q` parameter as option from NGSpeciesID parameters.

**Comment by pecholleyn** [comment]
Hi, I made a pull request for this feature, please review it

**Comment by ksahlin** [comment]
Thanks! I reviewed and merged into main.
