### ISSUE TITLE
Remove primer sequence

### ISSUE THREAD

**Issue by DuttaAnik** [ksahlin/NGSpeciesID#32]
Hi,
Is it possible to only remove primer sequences in ONT metabarcoded FASTQ files without generating the consensus sequence? I did basecalling with guppy and now want to remove some specific primers sequences that I used in the PCR before using the data for taxonomic classification.
Please let me know. 
Also, in some cases, I have only one primer that was used in the PCR.

**Comment by ksahlin** [comment]
Hi, 

NGSpeciesID has no such functionality. You probably want to have a look at https://github.com/epi2me-labs/pychopper and ask the question in their repo.
